# Generated by Django 3.2.5 on 2021-07-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='buy_from',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='deliver_to',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
