# Generated by Django 3.2.5 on 2021-07-15 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20210715_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, default='6c9827f2-71ef-4401-9f77-23644b95035c', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.user'),
            preserve_default=False,
        ),
    ]
